[package]
name = "acpi_machine_language"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.44"
quote = "1.0.34"

[lib]
proc-macro = true

