name: build
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Build the OS
        run: make build_on_github
      - name: Upload the OS
        uses: actions/upload-artifact@main
        with:
          name: An OS raw image
          path: HeliOS.img

