name: build
on:
  push:
    branches:
      - '*'
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Install ld.lld
        run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install lld -y
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Install rust nightly
        run: rustup toolchain install nightly
      - name: Install rust nightly-2024-01-01-x86_64-unknown-linux-gnu
        run: rustup toolchain install nightly-2024-01-01-x86_64-unknown-linux-gnu
      - name: Build the OS
        run: make
      - name: Upload the OS
        uses: actions/upload-artifact@main
        with:
          name: An OS raw image
          path: HeliOS.img

