name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Install ld.lld
        run: sudo apt-get install lld -y
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Build the OS
        run: make SUDO=sudo
      - name: Upload the OS
        uses: actions/upload-artifact@main
        with:
          name: An OS raw image
          path: HeliOS.img

