name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: actions/checkout@main
      - name: Build the OS
        run: make
      - name: Upload the OS
        uses: actions/upload-artifact@main
        with:
          name: An OS raw image
          path: $(make target)

